const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox']});const base=process.env.DREX_ROOM_TEST_URL||'http://127.0.0.1:8772';const errors=[];
async function page(){const ctx=await b.newContext({viewport:{width:1440,height:1000}});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.route('https://**/*',r=>r.abort());return p;}
const host=await page();await host.goto(base+'/command-room/');await host.click('[data-entry=create]');await host.fill('#name','훈련 통제');await host.selectOption('#speed','60');await host.waitForFunction(()=>!document.querySelector('#generate').disabled);await host.click('#generate');await host.locator('#draftPanel').waitFor({state:'visible'});assert.match(await host.locator('#generationSource').innerText(),/규칙 기반/);await host.click('#createRoom');await host.locator('#controller').waitFor({state:'visible'});assert.equal(await host.locator('#invites .invite').count(),13);
const fireLink=await host.locator('input[aria-label="소방 초대 링크"]').inputValue(),policeLink=await host.locator('input[aria-label="경찰 초대 링크"]').inputValue();
const fire=await page();await fire.goto(fireLink);await fire.fill('#joinName','소방 참가자');await fire.click('#joinForm button[type=submit]');await fire.locator('#workspace').waitFor({state:'visible'});assert.match(await fire.locator('#identity').innerText(),/소방/);assert.equal(await fire.locator('#role').count(),0);assert.equal(await fire.locator('#controller').isVisible(),false);assert.equal(await fire.locator('#ownJob option').count(),1);
const police=await page();await police.goto(policeLink);await police.fill('#joinName','경찰 참가자');await police.click('#joinForm button[type=submit]');await police.locator('#workspace').waitFor({state:'visible'});
await host.click('#startExercise');await fire.waitForFunction(()=>!document.querySelector('#request').disabled);await fire.selectOption('#requestJob','control');await fire.fill('#requestReason','구조 진입 전 위험구역 통제 요청');await fire.click('#request');await police.locator('[data-accept]').first().waitFor();await police.locator('[data-accept]').first().click();await police.waitForFunction(()=>document.querySelector('#resources').textContent.includes('남은 시간'));
await host.click('#advanceExercise');await fire.waitForFunction(()=>document.querySelector('#outbox').textContent.includes('완료'));await police.waitForFunction(()=>document.querySelector('#reports').textContent.includes('출입 통제 완료'));await police.locator('[data-share]').first().click();await fire.waitForFunction(()=>document.querySelector('#sharedReports').textContent.includes('출입 통제 완료'));
assert.match(await fire.locator('#identity').innerText(),/소방/);assert.match(await police.locator('#identity').innerText(),/경찰/);await fire.reload();await fire.locator('#workspace').waitFor({state:'visible'});assert.match(await fire.locator('#identity').innerText(),/소방/);
await fire.screenshot({path:'/tmp/drex-room-participant.png',fullPage:true});await host.screenshot({path:'/tmp/drex-room-controller.png',fullPage:true});
await host.click('#endExercise');await fire.locator('#aar').waitFor({state:'visible'});assert.equal(await fire.locator('#checklist h3').count(),1);const dl=fire.waitForEvent('download');await fire.click('#downloadReport');await(await dl).saveAs('/tmp/drex-room-report.html');
await fire.setViewportSize({width:390,height:844});assert.equal(await fire.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await fire.screenshot({path:'/tmp/drex-room-mobile.png',fullPage:true});
const solo=await page();await solo.goto('file://'+process.cwd()+'/command-room/preview.html');await solo.fill('#name','개인 연습자');await solo.selectOption('#myOrg','police');await solo.selectOption('#speed','5');await solo.click('#generate');await solo.locator('#draftPanel').waitFor({state:'visible'});await solo.click('#createRoom');await solo.locator('#workspace').waitFor({state:'visible'});assert.match(await solo.locator('#identity').innerText(),/경찰/);assert.equal(await solo.locator('.seat.auto').count(),12);await solo.waitForFunction(()=>document.querySelector('#clock').textContent!=='0분',{timeout:12000});assert.match(await solo.locator('#inbox').innerText(),/본인 기관/);assert.deepEqual(errors,[]);console.log('PASS: separate controller/fire/police sessions, 13 invitations, fixed roles, live requests/results/sharing, reconnect, scoped AAR/download, mobile, offline solo automatic partners');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
