import test from 'node:test';import assert from 'node:assert/strict';
import {makeRoomHandler} from '../server/command-room-service.mjs';import {ORGS,buildScenario} from '../command-room/model.mjs';
function harness(){let time=1700000000000;const rows=new Map();let collision=0;const store={health:async()=>true,insert:async r=>rows.set(r.id,structuredClone(r)),get:async id=>structuredClone(rows.get(id)),update:async(id,revision,payload)=>{if(collision){collision--;return false;}const r=rows.get(id);if(r.revision!==revision)return false;rows.set(id,{...r,revision:revision+1,payload:structuredClone(payload)});return true;}};const handle=makeRoomHandler(store,{now:()=>time});return {rows,step:n=>time+=n*15000,collision:n=>collision=n,call:async(body,token)=>{const r=await handle(new Request('https://drex.test/api/command-room',{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(body)}));return {http:r.status,...await r.json()};}};}
const create=async(h,solo=false,org='fire',auto=true)=>h.call({op:'create',scenario:buildScenario({},7),mode:'practice',name:'담당자',solo,org,auto});
const cmd=(h,room,command,id=crypto.randomUUID())=>h.call({op:'command',id:room.id,requestId:id,command},room.token);
const read=(h,room)=>h.call({op:'read',id:room.id},room.token);
const join=(h,host,org)=>h.call({op:'join',id:host.id,org,invite:host.invites[org],name:ORGS[org]+' 참가자'});

test('13개 기관 개별 입장·고정 역할·정보 투영·통제자 분리',async()=>{const h=harness(),host=await create(h,false,'fire',false),members={};assert.equal(host.http,200);for(const org of Object.keys(ORGS)){members[org]=await join(h,host,org);assert.equal(members[org].member.org,org);assert.equal(members[org].world,null);assert.equal(members[org].invites,undefined);assert.ok(members[org].reports.every(r=>r.org===org));}assert.equal((await cmd(h,host,{type:'start'})).http,200);const fire=members.fire,police=members.police;
 assert.equal((await cmd(h,fire,{type:'advance',minutes:5})).http,403);assert.equal((await cmd(h,host,{type:'dispatch',job:'rescue',reason:'대신 수행'})).http,403);assert.equal((await cmd(h,fire,{type:'dispatch',org:'police',job:'control',reason:'권한 변경 시도'})).http,403);
 const before=await read(h,police);assert.ok(!before.reports.some(r=>r.org==='fire'));await cmd(h,fire,{type:'share',id:fire.reports[0].id});const after=await read(h,police);assert.ok(after.reports.some(r=>r.org==='fire'&&r.shared));
});
test('기관별 초대 링크는 다른 기관 권한을 주지 않는다',async()=>{const h=harness(),host=await create(h);const wrong=await h.call({op:'join',id:host.id,org:'police',invite:host.invites.fire,name:'잘못된 입장'});assert.equal(wrong.http,403);await join(h,host,'fire');assert.equal((await join(h,host,'fire')).http,409);assert.equal((await h.call({op:'read',id:host.id},'wrong')).http,401);});
test('다른 참가자에게 협조 요청·수락·결과 전달, 기관 변경 불가',async()=>{const h=harness(),host=await create(h),fire=await join(h,host,'fire'),police=await join(h,host,'police');await cmd(h,host,{type:'start'});let a=await cmd(h,fire,{type:'request',job:'control',reason:'진입 통제 필요'});const q=a.requests[0];assert.equal((await cmd(h,fire,{type:'accept',id:q.id})).http,403);let p=await read(h,police);assert.equal(p.requests[0].id,q.id);await cmd(h,police,{type:'accept',id:q.id});h.step(4);a=await read(h,fire);assert.equal(a.requests[0].status,'done');assert.match(a.requests[0].result,/완료/);assert.equal(a.member.org,'fire');});
test('동시 요청과 재전송은 유실·중복 없이 처리된다',async()=>{const h=harness(),host=await create(h),fire=await join(h,host,'fire'),police=await join(h,host,'police');await cmd(h,host,{type:'start'});const [a,b]=await Promise.all([cmd(h,fire,{type:'request',job:'medical',reason:'의료 준비 협의'}),cmd(h,police,{type:'request',job:'road',reason:'도로 확인 요청'})]);assert.equal(a.http,200);assert.equal(b.http,200);const id=crypto.randomUUID();await cmd(h,fire,{type:'request',job:'power',reason:'안전 확인'},id);await cmd(h,fire,{type:'request',job:'power',reason:'안전 확인'},id);const v=await read(h,host);assert.equal(v.requests.length,3);h.collision(2);assert.equal((await cmd(h,fire,{type:'decision',reason:'통제 확인 후 진입'})).http,200);});
test('개인 연습은 본인 역할 고정·나머지 기관 자동 대응·시간 자동 진행',async()=>{const h=harness(),user=await create(h,true,'fire');assert.equal(user.member.kind,'participant');assert.equal(user.invites,undefined);assert.equal(user.participants.filter(p=>p.mode==='auto').length,12);h.step(1);let v=await read(h,user);assert.equal(v.time,1);assert.ok(v.requests.some(r=>r.to==='fire'&&r.source==='auto'));await cmd(h,user,{type:'request',job:'control',reason:'출입 통제 지원'});h.step(3);v=await read(h,user);assert.ok(v.requests.some(r=>r.job==='control'&&r.status==='active'));assert.equal(v.member.org,'fire');});
test('일시정지·재개·종료 후 점검표는 해당 기관 정보만 제공',async()=>{const h=harness(),host=await create(h),fire=await join(h,host,'fire');await cmd(h,host,{type:'start'});h.step(3);await cmd(h,host,{type:'pause'});h.step(10);assert.equal((await read(h,fire)).time,3);await cmd(h,host,{type:'resume'});h.step(2);assert.equal((await read(h,fire)).time,5);await cmd(h,host,{type:'end'});const v=await read(h,fire);assert.equal(v.aar.criteria.length,1);assert.equal(v.aar.criteria[0].org,'fire');assert.equal(v.aar.world,null);assert.equal((await cmd(h,fire,{type:'report',text:'종료 후 변경'})).http,400);});
test('생성 조건과 AI 실패 시 규칙 기반 전환',async()=>{const h=harness();const a=await h.call({op:'scenario',config:{location:'김해시 일대',kind:'fire',duration:30,lat:35.228,lng:128.889}});assert.equal(a.http,200);assert.equal(a.scenario.kind,'fire');assert.match(a.scenario.title,/김해/);assert.equal(a.scenario.duration,30);assert.equal(a.scenario.source,'template');assert.equal((await h.call({op:'scenario',config:{lat:1000}})).http,400);});

test('AI 생성 실패는 명시적으로 규칙 기반으로 전환된다',async()=>{
 const handle=makeRoomHandler({}, {generate:async()=>{throw Error('provider unavailable');}});
 const r=await handle(new Request('https://drex.test/api/command-room',{method:'POST',body:JSON.stringify({op:'scenario',config:{kind:'fire'}})}));
 const v=await r.json();assert.equal(r.status,200);assert.equal(v.scenario.source,'template');assert.match(v.notice,/AI 연결.*규칙 기반/);
});
