import test from 'node:test';import assert from 'node:assert/strict';import {makeHandler} from '../server/practical-service.mjs';import {DEFAULT_CHECKLIST,sample,restoreSession} from '../practical/engine.mjs';
export function memoryStore(){const rows=new Map();return {insert:async r=>rows.set(r.id,structuredClone(r)),get:async id=>structuredClone(rows.get(id)),update:async(id,v,p)=>{const r=rows.get(id);if(r.revision!==v)return false;rows.set(id,{...r,revision:v+1,payload:structuredClone(p)});return true;},rows};}
function client(handler){return async(body,token)=>{const res=await handler(new Request('http://localhost/api/practical',{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(body)}));return {status:res.status,...await res.json()};};}
test('공동훈련 인증·기관 권한·중복 요청·동시 저장',async()=>{const store=memoryStore(),call=client(makeHandler(store));const host=await call({op:'create',checklist:DEFAULT_CHECKLIST,title:'공동훈련'});assert.equal(host.status,200);const id=host.session.id;assert.equal((await call({op:'read',id})).status,401);assert.equal((await call({op:'join',id,invite:'wrong',agency:'경찰'})).status,403);const police=await call({op:'join',id,invite:host.invite,agency:'경찰',name:'김 담당'});assert.equal(police.member.agency,'경찰');assert.equal((await call({op:'join',id,invite:host.invite,agency:'경찰'})).status,409);let state=await call({op:'read',id},host.token);const cmd=async(c,who=host,rev=state.revision,rid=crypto.randomUUID())=>call({op:'command',id,revision:rev,requestId:rid,command:c},who.token);
 assert.equal((await cmd({type:'advance',minutes:1},police)).status,403);
 state=await cmd({type:'act',task:'control',kind:'request',agency:'지자체',text:'통제 요청'});assert.equal(state.status,200);
 assert.equal((await cmd({type:'act',task:'control',kind:'ack',agency:'소방'},police,state.revision-1)).status,409);
 const rid=crypto.randomUUID();state=await cmd({type:'act',task:'control',kind:'ack',agency:'소방'},police,state.revision,rid);assert.equal(state.status,200);assert.equal(state.session.events.at(-1).agency,'경찰');const count=state.session.events.length;const dup=await cmd({type:'act',task:'control',kind:'ack'},police,0,rid);assert.equal(dup.session.events.length,count);
 const results=await Promise.all([cmd({type:'advance',minutes:1}),cmd({type:'advance',minutes:1})]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);
 const raw=[...store.rows.values()][0];assert.ok(!JSON.stringify(raw).includes(host.token));assert.ok(!JSON.stringify(raw).includes(host.invite));
});
test('backup restoration rejects corrupt evidence and prototype identifiers',()=>{const s=sample();assert.equal(restoreSession(JSON.parse(JSON.stringify(s))).tasks.rescue.status,'completed');s.events[1].id=s.events[0].id;assert.throws(()=>restoreSession(s),/기록/);const x=sample();x.checklist[0].id='__proto__';assert.throws(()=>restoreSession(x),/항목 번호/);});
test('expired and cross-origin sessions are rejected',async()=>{const store=memoryStore(),handler=makeHandler(store),call=client(handler);const h=await call({op:'create',checklist:DEFAULT_CHECKLIST});store.rows.get(h.session.id).expires_at='2000-01-01';assert.equal((await call({op:'read',id:h.session.id},h.token)).status,404);const r=await handler(new Request('http://localhost/api/practical',{method:'POST',headers:{Origin:'https://other.example'},body:'{}'}));assert.equal(r.status,403);});
