const {chromium}=require('playwright');const assert=require('node:assert/strict');const http=require('node:http');const fs=require('node:fs/promises');const path=require('node:path');const {pathToFileURL}=require('node:url');
(async()=>{const {makeHandler}=await import(pathToFileURL(path.resolve('server/practical-service.mjs')));const rows=new Map();const handler=makeHandler({insert:async r=>rows.set(r.id,structuredClone(r)),get:async id=>structuredClone(rows.get(id)),update:async(id,v,p)=>{const r=rows.get(id);if(r.revision!==v)return false;rows.set(id,{...r,revision:v+1,payload:structuredClone(p)});return true;}});
const server=http.createServer(async(req,res)=>{try{if(req.url==='/api/practical'){let body='';for await(const x of req)body+=x;const out=await handler(new Request('http://127.0.0.1:8770/api/practical',{method:'POST',headers:req.headers,body}));res.writeHead(out.status,Object.fromEntries(out.headers));res.end(await out.text());return;}const url=new URL(req.url,'http://localhost');const rel=url.pathname.endsWith('/')?url.pathname+'index.html':url.pathname;const filename=path.resolve('.'+rel);if(!filename.startsWith(process.cwd()+path.sep)){res.writeHead(403);res.end();return;}const bytes=await fs.readFile(filename);res.setHeader('Content-Type',filename.endsWith('.mjs')?'text/javascript':filename.endsWith('.css')?'text/css':'text/html');res.end(bytes);}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(8770,'127.0.0.1',r));
const browser=await chromium.launch({...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{}),headless:true,args:['--no-sandbox']});try{const errors=[];const host=await browser.newPage(),agency=await browser.newPage();for(const p of [host,agency]){p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.goto('http://127.0.0.1:8770/practical/');await p.locator('#tasks .task').first().waitFor();await p.locator('#livePanel summary').click();}
await host.click('#liveCreate');await host.waitForFunction(()=>!document.querySelector('#inviteWrap').hidden);const invite=await host.inputValue('#inviteCode');await agency.fill('#joinCode',invite);await agency.selectOption('#joinAgency','경찰');await agency.fill('#joinName','경찰 담당');await agency.click('#liveJoin');await agency.waitForFunction(()=>document.querySelector('#liveState').textContent.includes('경찰'));assert.equal(await agency.locator('#actor').isDisabled(),true);assert.equal(await agency.locator('#advance').isDisabled(),true);
await host.waitForTimeout(3300);await host.click('[data-task="broadcast"][data-kind="request"]');await host.waitForFunction(()=>!document.querySelector('[data-task="broadcast"][data-kind="ack"]').disabled);await host.click('[data-task="broadcast"][data-kind="ack"]');await host.waitForFunction(()=>!document.querySelector('#advance').disabled);await host.click('#advance');await host.waitForFunction(()=>document.querySelector('#clock').textContent==='01분');await host.fill('[data-task-note="broadcast"]','전파 확인');await host.click('[data-task="broadcast"][data-kind="complete"]');await host.waitForFunction(()=>document.querySelector('.task.done'));
await host.click('[data-task="control"][data-kind="request"]');await agency.waitForFunction(()=>!document.querySelector('[data-task="control"][data-kind="ack"]').disabled);await agency.click('[data-task="control"][data-kind="ack"]');await host.waitForFunction(()=>document.querySelector('[data-task="control"][data-kind="request"]').closest('article').textContent.includes('접수됨'));assert.match(await host.locator('#timeline').innerText(),/경찰/);
await agency.reload();await agency.locator('#tasks .task').first().waitFor();await agency.waitForFunction(()=>document.querySelector('#actor').value==='경찰');assert.equal(await agency.locator('#actor').isDisabled(),true);
await host.click('#end');await agency.waitForFunction(()=>document.querySelector('#status').textContent==='종료');await agency.click('[data-tab="report"]');assert.match(await agency.locator('#reportView').innerText(),/경찰 담당 참여/);
await agency.locator('#livePanel summary').click();await agency.click('#liveLeave');await agency.click('#liveResume');await agency.waitForFunction(()=>document.querySelector('#status').textContent==='종료');assert.deepEqual(errors,[]);console.log('PASS: two independent browser contexts, host create, agency join, enforced role, shared requests and acceptance, refresh, end sync, report, reconnect');}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exit(1)});
