import test from 'node:test';import assert from 'node:assert/strict';
import {newSession,start,advance,act,evaluate,review,validateChecklist,sample,report,summary,evidence} from '../practical/engine.mjs';
test('기관 역할·요청 순서·작업시간·선행조건을 강제한다',()=>{const s=newSession();assert.throws(()=>act(s,'rescue','request','지자체'));start(s);assert.throws(()=>act(s,'rescue','ack','소방'));act(s,'rescue','request','지자체');assert.throws(()=>act(s,'rescue','ack','경찰'));act(s,'rescue','ack','소방');advance(s,5);assert.throws(()=>act(s,'rescue','complete','소방','구조 완료'),/선행/);act(s,'broadcast','request','지자체');act(s,'broadcast','ack','지자체');assert.throws(()=>act(s,'broadcast','complete','지자체','확인'),/1분/);advance(s);assert.throws(()=>act(s,'broadcast','complete','지자체',''),/근거/);act(s,'broadcast','complete','지자체','전파 확인');assert.throws(()=>act(s,'broadcast','complete','지자체','중복'));});
test('샘플은 정상·지연·부분 조치·기록 부족을 구별한다',()=>{const s=sample();assert.deepEqual(evaluate(s).map(r=>r.verdict),['충족','충족','충족','부분 충족','확인 필요','부분 충족']);const q=summary(s);assert.equal(q.earned,67.5);assert.equal(q.assessedMax,85);assert.equal(q.applicableMax,100);assert.equal(q.unresolved,1);assert.match(report(s),/최종 총점이 아닙니다/);assert.match(report(s),/미확정/);});
test('보완 근거가 없으면 미충족으로 단정하지 않으며 수동 판정에 근거를 요구한다',()=>{const s=sample();assert.throws(()=>review(s,'C5','충족','전화 확인',[]),/근거/);assert.throws(()=>review(s,'C5','충족','전화 확인',['E999']),/존재하지/);evidence(s,'보건','훈련 18분 구두 인계 기록 확인');const id=s.events.at(-1).id;review(s,'C5','충족','외부 인계 확인',[id]);assert.equal(evaluate(s)[4].points,15);assert.match(report(s),new RegExp(id));});
test('해당 없음은 적용 배점에서 제외하며 사용자 기준을 적용한다',()=>{const s=sample();review(s,'C5','해당 없음','이번 회차 이송 제외');assert.equal(summary(s).applicableMax,85);assert.equal(summary(s).unresolved,0);s.checklist=validateChecklist([{id:'X',title:'별도 점검',criterion:'외부 근거 확인',task:'',weight:12,deadline:5,partial:.25}]);assert.equal(evaluate(s)[0].verdict,'확인 필요');});
test('중복·유효하지 않은 기준은 거부한다',()=>{const s=newSession();assert.throws(()=>validateChecklist([s.checklist[0],s.checklist[0]]),/중복/);for(const patch of [{weight:-1},{deadline:'bad'},{partial:2},{task:'unknown'}])assert.throws(()=>validateChecklist([{...s.checklist[0],...patch}]));});
test('시간은 명시적 진행만 반영하고 종료 후 조치는 금지한다',async()=>{const s=newSession();start(s);await new Promise(r=>setTimeout(r,10));assert.equal(s.minute,0);advance(s,2);assert.equal(s.minute,2);s.status='ended';assert.throws(()=>advance(s));assert.throws(()=>act(s,'broadcast','request','지자체'));});
test('도움말 사용과 점검 근거는 보고서에 남는다',()=>{const s=newSession();start(s);act(s,'broadcast','request','지자체','전파 요청',true);assert.equal(evaluate(s)[0].assisted,true);assert.match(report(s),/도움말 사용: 있음/);});
