// Local/LAN training server with durable SQLite storage. Production uses Supabase.
import http from 'node:http';import {DatabaseSync} from 'node:sqlite';import {readFile} from 'node:fs/promises';import path from 'node:path';
import {makeRoomHandler} from '../server/command-room-service.mjs';
const db=new DatabaseSync(process.env.DREX_ROOM_DB||'/tmp/drex-command-rooms.sqlite');db.exec('CREATE TABLE IF NOT EXISTS rooms (id TEXT PRIMARY KEY, revision INTEGER, payload TEXT, expires_at TEXT)');
const store={health:async()=>true,insert:async r=>db.prepare('INSERT INTO rooms VALUES(?,?,?,?)').run(r.id,r.revision,JSON.stringify(r.payload),r.expires_at),get:async id=>{const r=db.prepare('SELECT * FROM rooms WHERE id=?').get(id);return r?{...r,payload:JSON.parse(r.payload)}:null;},update:async(id,revision,payload)=>db.prepare('UPDATE rooms SET payload=?,revision=revision+1 WHERE id=? AND revision=?').run(JSON.stringify(payload),id,revision).changes===1};
const handle=makeRoomHandler(store),root=path.resolve(import.meta.dirname,'..'),port=Number(process.env.PORT||8772);
http.createServer(async(req,res)=>{try{
 const url=new URL(req.url,'http://'+req.headers.host);if(url.pathname==='/api/command-room'){const bufs=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>50000){res.writeHead(413);res.end();return;}bufs.push(chunk);}const out=await handle(new Request(url,{method:req.method,headers:req.headers,...(req.method==='POST'?{body:Buffer.concat(bufs)}:{})}));res.writeHead(out.status,Object.fromEntries(out.headers));res.end(await out.text());return;}
 let rel=decodeURIComponent(url.pathname);if(rel==='/'||rel==='/command-sim/'||rel==='/command-room/')rel='/command-room/index.html';const file=path.resolve(root,'.'+rel);if(!file.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}const data=await readFile(file),ext=path.extname(file);res.writeHead(200,{'Content-Type':{'.html':'text/html; charset=utf-8','.mjs':'text/javascript','.js':'text/javascript','.css':'text/css'}[ext]||'application/octet-stream'});res.end(data);
 }catch{res.writeHead(404);res.end('Not found');}}).listen(port,process.env.DREX_BIND||'127.0.0.1',()=>console.log('DREX room server http://127.0.0.1:'+port));
