import {ORGS,JOBS,ORG_GUIDE} from './model.mjs';
import {makeLocalRequest} from './local-runtime.mjs';
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const CRED='drex-room-credential-v1';let entryKind='solo',draft=null,credential=null,current=null,localMode=location.protocol==='file:',localRequest=null,busy=false,polling=false,pending=null,lastSync=0,initialView=true,mapObj=null,markers=null,tile=null,tileMode='sat',mapRoom=null,lastError='';
function toast(t){$('toast').textContent=t;$('toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('visible'),5500);}
function saveCredential(){try{localStorage.setItem(CRED,JSON.stringify(credential));}catch{toast('자동 저장이 불가능합니다. 내 접속코드를 파일로 저장하세요.');}}
async function rpc(body,withAuth=true){
 const headers={'Content-Type':'application/json',...(withAuth&&credential?{Authorization:'Bearer '+credential.token}:{})};let r;
 if(localMode){localRequest ||= makeLocalRequest();r=await localRequest(new Request('http://localhost/api/command-room',{method:'POST',headers,body:JSON.stringify(body)}));}
 else r=await fetch('/api/command-room',{method:'POST',headers,body:JSON.stringify(body),signal:AbortSignal.timeout(body.op==='scenario'?25000:15000)});
 let data;try{data=await r.json();}catch{throw Error('서버 응답을 읽지 못했습니다. 배포 주소와 연결 상태를 확인하세요.');}if(!r.ok){const e=Error(data.error||'요청 처리 실패');e.status=r.status;throw e;}return data;
}
function download(name,data,type='application/json'){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function takeView(v){if(current&&current.id===v.id&&v.revision<current.revision)return;current=v;lastSync=Date.now();lastError='';if(v.token){credential={id:v.id,token:v.token,local:localMode};saveCredential();}render();}
async function sendCommand(c,retry=false){if(busy)return;busy=true;try{
 if(!retry){if(pending){toast('전송 결과가 확인되지 않은 조치가 있습니다. 다시 보내기로 먼저 확인하세요.');return;}pending={requestId:crypto.randomUUID(),command:c};}
 $('retryCommand').hidden=true;const v=await rpc({op:'command',id:credential.id,...pending});pending=null;takeView(v);toast('조치가 반영되었습니다.');
 }catch(e){lastError=e.message;if(e.status&&e.status!==409&&e.status<500)pending=null;$('retryCommand').hidden=!pending;toast(e.message);renderConnection();}finally{busy=false;}}
async function poll(){if(!credential||polling||busy||$('workspace').hidden)return;polling=true;try{takeView(await rpc({op:'read',id:credential.id}));}catch(e){lastError=e.message;renderConnection();}finally{polling=false;}}
async function health(){
 if(localMode){$('health').className='statusBox';$('health').textContent='이 기기의 개인 연습입니다. 공동 로그인·다른 기기 접속은 웹 서버 연결이 필요합니다.';$('generate').disabled=false;$('offline').hidden=true;return;}
 $('health').textContent='공동훈련 서버 연결 확인 중…';try{const h=await rpc({op:'health'},false);$('health').className='statusBox good';$('health').textContent='공동훈련 서버 연결됨. '+(h.ai?'AI 시나리오 서술 사용 가능.':'규칙 기반 시나리오 자동 구성 사용 가능.');$('generate').disabled=false;$('offline').hidden=true;}
 catch(e){$('health').className='statusBox error';$('health').textContent=e.message+' 합동훈련은 연결 복구 후 사용할 수 있습니다.';$('generate').disabled=true;$('offline').hidden=entryKind!=='solo';}
}
function chooseEntry(kind){requestAnimationFrame(()=>pickerMap?.invalidateSize());entryKind=kind;draft=null;$('draftPanel').hidden=true;$('setupForm').hidden=kind==='join';$('joinForm').hidden=kind!=='join';$('orgField').hidden=kind!=='solo';$('autoField').hidden=kind!=='create';$('setupTitle').textContent=kind==='solo'?'내 기관으로 개인 연습':'합동훈련 개설 · 통제자';document.querySelectorAll('[data-entry]').forEach(b=>b.classList.toggle('chosen',b.dataset.entry===kind));if(localMode&&kind!=='solo'){$('health').className='statusBox error';$('health').textContent='현재는 이 기기의 개인 연습입니다. 합동훈련은 서버에 배포된 주소에서 개설·입장하세요.';$('generate').disabled=true;}else health();}
function parseInvite(value){const u=new URL(value,location.href),q=new URLSearchParams(u.hash.slice(1));const id=q.get('room'),org=q.get('org'),invite=q.get('invite');if(!id||!ORGS[org]||!invite)throw Error('기관별 초대 링크 전체를 입력하세요.');return{id,org,invite};}
function inviteLink(org){const u=new URL('/command-room/',location.href);u.hash=new URLSearchParams({room:current.id,org,invite:current.invites[org]}).toString();return u.href;}
function setupOptions(){const options=Object.entries(ORGS).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');$('myOrg').innerHTML=options;$('injectOrg').innerHTML=options;$('requestJob').innerHTML=Object.entries(JOBS).map(([k,j])=>`<option value="${k}">${ORGS[j.org]} · ${j.name}</option>`).join('');}
function renderConnection(){const local=localMode?'개인 연습 · 이 기기에 저장':'공동훈련 · 서버 연결';$('connection').className='statusBox'+(lastError?' error':' good');$('connection').textContent=lastError?'연결 확인 필요: '+lastError+' 마지막 수신 '+new Date(lastSync).toLocaleTimeString('ko-KR'):local+' / '+(current?.status==='running'?`시간 자동 진행: 실제 ${current.scenario.secondsPerMinute}초마다 훈련 1분`:'훈련 상태: '+statusName(current?.status));}
const statusName=s=>({lobby:'참가자 입장 대기',running:'진행 중',paused:'일시정지',ended:'종료'})[s]||s;
const reqStatus=s=>({pending:'회신 대기',active:'수행 중',done:'완료',declined:'조정 회신'})[s];
function requestHTML(r,incoming){return `<article class="item"><div class="meta">${r.time}분 · ${ORGS[r.from]} → ${ORGS[r.to]} · ${r.source==='auto'?'자동 대응':'참가자'}</div><strong>${JOBS[r.job].name}</strong><p>${esc(r.reason)}</p><span class="badge">${reqStatus(r.status)}</span>${r.reply?'<p>회신: '+esc(r.reply)+'</p>':''}${r.result?'<p>'+esc(r.result)+'</p>':''}${incoming&&r.status==='pending'&&current.status==='running'?`<div class="actions"><button class="primary" data-accept="${r.id}">요청 수락·조치 시작</button><button data-decline="${r.id}">지원 조정·대안 회신</button></div>`:''}</article>`;}
function reportHTML(r,own){return `<article class="item"><div class="meta">${r.time}분 · ${ORGS[r.org]} · ${r.shared?'공동 공유':'기관 수신'}${r.source==='controller'?' · 통제 부여':''}</div><p>${esc(r.text)}</p>${own&&!r.shared&&current.status==='running'?`<button data-share="${r.id}">다른 기관에 공유</button>`:''}</article>`;}
function render(){
 const v=current;if(!v)return;const control=v.member.kind==='control',org=v.member.org,own=org?v.reports.filter(r=>r.org===org):[];
 $('entry').hidden=true;$('workspace').hidden=false;$('sessionTitle').textContent=v.scenario.title;$('sessionMode').textContent=(v.mode==='practice'?'연습훈련':'실제훈련')+' / '+(v.solo?'개인 연습':'합동훈련');$('identity').textContent=control?'훈련통제자':ORGS[org]+' · '+v.member.name;$('clock').textContent=v.time+'분';$('sessionStatus').textContent=statusName(v.status);renderConnection();
 $('controller').hidden=!control;$('participant').hidden=control;$('endSolo').hidden=!v.solo||v.status==='ended';$('guide').hidden=v.mode!=='practice'||v.status==='ended';$('waitingRoom').hidden=v.status!=='lobby';
 if(control){
  const n=v.participants.filter(p=>p.mode==='human').length;$('controllerGuide').textContent=`현재 ${n}/13개 기관 입장. 참가자는 자기 기관의 업무만 수행합니다. ${v.auto?'나머지 기관은 규칙 기반 자동 대응으로 보완합니다.':'모든 기관 입장 후 시작할 수 있습니다.'}`;
  $('startExercise').disabled=v.status!=='lobby';$('pauseExercise').disabled=!['running','paused'].includes(v.status);$('pauseExercise').textContent=v.status==='paused'?'훈련 재개':'일시정지';$('advanceExercise').disabled=v.status!=='running';$('endExercise').disabled=!['running','paused'].includes(v.status);$('controllerAuto').checked=v.auto;$('controllerAuto').disabled=v.status!=='lobby';
  $('truth').textContent=`통제자 모의 상태: 고립 잔류 ${v.world.trapped}명 / 대피 잔류 ${v.world.evacuees}명 / 구조 ${v.world.rescued}명 / 대피 ${v.world.evacuated}명 / 접근로 ${v.world.roadBlocked?'단절':'통행 가능'}`;
  $('invites').innerHTML=v.participants.map(p=>`<div class="invite"><span>${p.name}<small> ${p.mode==='human'?'입장 완료':p.mode==='auto'?'자동 대응':'미참여'}</small></span><input aria-label="${p.name} 초대 링크" readonly value="${esc(inviteLink(p.org))}"><button data-copy="${p.org}">링크 복사</button></div>`).join('');
 }else{
  if(initialView){$('ownJob').innerHTML=Object.entries(JOBS).filter(([,j])=>j.org===org).map(([k,j])=>`<option value="${k}">${j.name}</option>`).join('');initialView=false;}
  const incoming=v.requests.filter(r=>r.to===org),out=v.requests.filter(r=>r.from===org);$('inCount').textContent=incoming.filter(r=>r.status==='pending').length+'건 대기';$('inbox').innerHTML=incoming.length?incoming.slice().reverse().map(r=>requestHTML(r,true)).join(''):'<p class="empty">아직 받은 요청이 없습니다. 우리 기관의 보고를 확인하고 필요한 조치를 직접 시작할 수 있습니다.</p>';
  $('outbox').innerHTML=out.length?out.slice().reverse().map(r=>requestHTML(r,false)).join(''):'<p class="empty">다른 기관의 지원이 필요하면 위에서 요청하세요.</p>';
  const res=v.resources[org];$('resourceCount').textContent=`가용 ${res.capacity-res.jobs.length} / 전체 ${res.capacity}`;$('resources').innerHTML=res.jobs.map(j=>`<p>${JOBS[j.job].name} · 남은 시간 ${j.remaining}분</p>`).join('')||'<p>배정된 임무가 없습니다.</p>';
  $('reportCount').textContent=own.length+'건';$('reports').innerHTML=own.slice().reverse().map(r=>reportHTML(r,true)).join('');
  const pendingRequest=incoming.find(r=>r.status==='pending'),unshared=own.find(r=>!r.shared);let title='',text='',target='reports';
  if(v.status==='lobby'){title='입장했습니다. 본인 기관의 초기 보고를 읽어보세요.';text='통제자가 시작하면 조치 버튼을 사용할 수 있습니다.';}
  else if(pendingRequest){title=ORGS[pendingRequest.from]+'의 지원 요청을 확인하세요.';text=JOBS[pendingRequest.job].name+' 요청입니다. 자원을 확인한 뒤 수락하거나 대안을 회신하세요.';target='inbox';}
  else if(unshared){title='우리 기관이 받은 정보를 확인하고 공유하세요.';text=unshared.text;}
  else if(res.jobs.length){title='조치가 진행 중입니다. 다른 기관 회신을 확인하세요.';text='시간은 자동으로 진행됩니다. 완료 보고가 도착하면 확인하고 공유하세요.';target='outbox';}
  else{title='다음 조치를 판단하거나 필요한 지원을 요청하세요.';text=ORG_GUIDE[org];target='ownReason';}
  $('nextTitle').textContent=title;$('nextText').textContent=text;$('nextButton').onclick=()=>$(target).scrollIntoView({behavior:'smooth',block:'center'});
  for(const id of ['dispatch','request','report'])$(id).disabled=v.status!=='running';
 }
 $('participants').innerHTML=v.participants.map(p=>`<div class="seat ${p.mode}"><strong>${p.name}</strong><small>${p.mode==='human'?'참가자: '+esc(p.members.join(', ')):p.mode==='auto'?'자동 대응 · 규칙 기반':'아직 입장하지 않음'}</small></div>`).join('');
 $('sharedReports').innerHTML=v.reports.filter(r=>r.shared).slice(-10).reverse().map(r=>reportHTML(r,false)).join('')||'<p class="empty">공유된 보고가 없습니다. 기관 보고를 공유하면 여기에 표시됩니다.</p>';
 $('events').innerHTML=v.events.slice(-60).reverse().map(e=>`<div class="event"><time>${e.time}분</time><span>${ORGS[e.org]||'훈련통제'}${e.source==='auto'?' [자동]':''} · ${esc(e.text)}</span></div>`).join('');
 $('aar').hidden=v.status!=='ended';if(v.aar){$('checklist').innerHTML=v.aar.criteria.map(c=>`<h3>${ORGS[c.org]}</h3>${c.checks.map(x=>`<div class="checkRow"><div>${x.name}<small>근거: ${x.ids.length?x.ids.join(', '):'기록 미확인'}</small></div><strong class="checkState ${x.met?'met':''}">${x.met?'기록 확인':'검토 필요'}</strong></div>`).join('')}`).join('');$('showReport').textContent='점검표·훈련 보고서';}
 updateMap();
}
function updateMap(){
 if(!globalThis.L)return;const s=current.scenario;
 if(!mapObj){mapObj=L.map('roomMap').setView([s.lat,s.lng],14);markers=L.layerGroup().addTo(mapObj);setTiles('sat');L.control.scale({imperial:false}).addTo(mapObj);$('mapDetails').ontoggle=()=>mapObj.invalidateSize();}
 if(mapRoom!==current.id){mapObj.setView([s.lat,s.lng],14);mapRoom=current.id;}
 markers.clearLayers();const positions={center:[0,0],rescue:[.004,.002],care:[-.006,.007],road:[.012,-.01],hospital:[-.01,-.008],shelter:[-.006,-.015]},names={center:'훈련 중심',rescue:'구조 지점',care:'대피 출발',road:'접근로',hospital:'의료지원',shelter:'대피소'};
 const known=new Set(current.reports.map(r=>r.site));for(const key of known){const d=positions[key];if(!d)continue;L.marker([s.lat+d[0],s.lng+d[1]],{icon:L.divIcon({className:'',html:`<div class="mapLabel">${names[key]}<br><small>훈련 가정 위치</small></div>`,iconSize:[150,58],iconAnchor:[key==='shelter'?145:15,29]})}).addTo(markers);}
 requestAnimationFrame(()=>mapObj.invalidateSize());
}
function setTiles(kind){if(!mapObj)return;tileMode=kind;if(tile)mapObj.removeLayer(tile);const sat=kind==='sat';tile=L.tileLayer('https://services.arcgisonline.com/ArcGIS/rest/services/'+(sat?'World_Imagery':'World_Topo_Map')+'/MapServer/tile/{z}/{y}/{x}',{maxZoom:18,...(!sat?{maxNativeZoom:12}:{}),attribution:sat?'Imagery © Esri, Maxar, Earthstar Geographics, GIS User Community':'Tiles © Esri, USGS, NGA, NASA, GIS User Community'}).addTo(mapObj);$('mapStatus').textContent='배경지도 연결 중…';let loaded=0,errors=0;tile.on('tileload',()=>{loaded++;$('mapStatus').textContent=sat?'실제 항공영상 · 실시간 아님 / 사건 위치는 훈련 가정':'일반지도 · 지역 개요 수준 / 상세 확대 제한';});tile.on('tileerror',()=>{if(++errors>=3&&!loaded)$('mapStatus').textContent='배경지도 수신 실패. 다른 배경지도를 선택하세요. 훈련은 계속할 수 있습니다.';});}
function reportHTMLDocument(){const a=current.aar;return `<!doctype html><html lang="ko"><meta charset="utf-8"><title>DREX 훈련 보고서</title><style>body{max-width:950px;margin:40px auto;padding:20px;font:17px/1.8 sans-serif;color:#234357}table{width:100%;border-collapse:collapse}th,td{border:1px solid #b7cbd6;padding:10px;text-align:left}pre{white-space:pre-wrap;font:inherit}</style><h1>${esc(a.title)}</h1><p>${current.member.kind==='control'?'통제자 종합':esc(ORGS[current.member.org])} / ${a.time}분 / ${current.mode==='practice'?'연습훈련':'실제훈련'}</p><p>${esc(a.note)}</p>${a.criteria.map(c=>`<h2>${ORGS[c.org]}</h2><table><tr><th>점검 항목</th><th>확인</th><th>근거</th></tr>${c.checks.map(x=>`<tr><td>${x.name}</td><td>${x.met?'기록 확인':'검토 필요'}</td><td>${x.ids.join(', ')||'기록 미확인'}</td></tr>`).join('')}</table>`).join('')}<h2>당시 판단과 이용 가능한 정보</h2>${a.decisions.map(d=>`<h3>${d.time}분 · ${ORGS[d.org]} · ${esc(d.type)}</h3><p>${esc(d.reason)||'행동 기록'}</p><ul>${d.reports.map(r=>`<li>${r.id} (${r.time}분) ${esc(r.text)}</li>`).join('')}</ul>`).join('')}<h2>강평·개선계획</h2><pre>${esc($('improvements').value)||'담당자가 검토 후 작성합니다.'}</pre><p>모의규칙에 따른 교육용 결과이며 실제 피해 예측이나 공식 평가 판정이 아닙니다.</p></html>`;}
setupOptions();document.querySelectorAll('[data-entry]').forEach(b=>b.onclick=()=>chooseEntry(b.dataset.entry));$('help').onclick=()=>$('helpDialog').showModal();$('closeHelp').onclick=()=>$('helpDialog').close();
const regionPresets={danyang:['단양군 단양읍 일대',36.99,128.365],sejong:['세종시 일대',36.48,127.289],gimhae:['김해시 일대',35.228,128.889]};
let pickerMap=null,pickerMarker=null,pickerTile=null,selectedPoint=[36.99,128.365],pointConfirmed=true;
function invalidateDraft(){draft=null;$('draftPanel').hidden=true;}
function pointLabel(){ $('selectedLocation').textContent=(pointConfirmed?'선택한 훈련 중심: ':'지도에서 위치를 다시 선택하세요: ')+$('locationName').value+' · '+selectedPoint.map(n=>n.toFixed(5)).join(', '); }
function selectPoint(lat,lng,pan=false){
 if(!Number.isFinite(lat)||!Number.isFinite(lng)||lat < -85||lat > 85||lng < -180||lng > 180)return toast('위도 -85~85, 경도 -180~180 범위로 입력하세요.');
 selectedPoint=[lat,lng];pointConfirmed=true;$('coordinates').value=selectedPoint.map(n=>n.toFixed(6)).join(', ');invalidateDraft();pointLabel();
 if(pickerMap){if(pickerMarker)pickerMarker.setLatLng(selectedPoint);else{pickerMarker=L.marker(selectedPoint,{draggable:true,icon:L.divIcon({className:'centerPin',html:'<span>훈련 중심</span>',iconSize:[92,36],iconAnchor:[46,36]})}).addTo(pickerMap);pickerMarker.on('dragend',()=>{const p=pickerMarker.getLatLng();selectPoint(p.lat,p.lng);});}if(pan)pickerMap.setView(selectedPoint,14);}
}
function pickerTiles(kind){if(!pickerMap)return;if(pickerTile)pickerMap.removeLayer(pickerTile);const sat=kind==='sat';$('pickSat').setAttribute('aria-pressed',String(sat));$('pickStreet').setAttribute('aria-pressed',String(!sat));$('pickStatus').textContent='배경지도 연결 중…';let loaded=0;
 pickerTile=L.tileLayer('https://services.arcgisonline.com/ArcGIS/rest/services/'+(sat?'World_Imagery':'World_Topo_Map')+'/MapServer/tile/{z}/{y}/{x}',{maxZoom:18,...(!sat?{maxNativeZoom:12}:{}),attribution:'Tiles © Esri and contributors'}).addTo(pickerMap);
 pickerTile.on('tileload',()=>{loaded++;$('pickStatus').textContent=sat?'항공영상 · 실시간 영상이 아닙니다. 핀을 끌어서 위치를 조정할 수도 있습니다.':'일반지도 · 광역 확인용. 세부 위치는 항공영상에서 확인하세요.';});pickerTile.on('tileerror',()=>{if(!loaded)$('pickStatus').textContent='배경지도를 불러오지 못했습니다. 다른 지도를 선택하거나 좌표 직접 입력을 이용하세요.';});
}
if(window.L){pickerMap=L.map('locationMap',{scrollWheelZoom:false}).setView(selectedPoint,14);L.control.scale({imperial:false}).addTo(pickerMap);pickerMap.on('click',e=>selectPoint(e.latlng.lat,e.latlng.lng));pickerTiles('sat');selectPoint(...selectedPoint);}else{$('pickStatus').textContent='지도를 불러오지 못했습니다. 보조 기능에서 좌표를 입력하세요.';pointLabel();}
$('pickSat').onclick=()=>pickerTiles('sat');$('pickStreet').onclick=()=>pickerTiles('street');$('pickCenter').onclick=()=>{if(pickerMap){const c=pickerMap.getCenter();selectPoint(c.lat,c.lng);}};
$('applyCoordinates').onclick=()=>{const parts=$('coordinates').value.split(',');if(parts.length!==2||parts.some(x=>!x.trim()))return toast('위도, 경도를 쉼표로 구분해 입력하세요.');selectPoint(...parts.map(Number),true);};
$('coordinates').oninput=()=>{pointConfirmed=false;invalidateDraft();pointLabel();};
$('locationName').oninput=()=>{$('region').value='custom';pointConfirmed=false;invalidateDraft();pointLabel();};
$('region').onchange=()=>{const p=regionPresets[$('region').value];if(p){$('locationName').value=p[0];selectPoint(p[1],p[2],true);}else{pointConfirmed=false;invalidateDraft();pointLabel();$('locationName').focus();}};
$('setupForm').onsubmit=async e=>{e.preventDefault();if(localMode&&entryKind!=='solo')return toast('합동훈련은 서버 연결이 필요합니다.');$('generate').disabled=true;$('generate').textContent='시나리오 생성 중…';try{
 const location=$('locationName').value.trim(),[lat,lng]=selectedPoint;
 if(!location)throw Error('훈련지역 또는 주소를 입력하세요.');
 if(!pointConfirmed)throw Error('입력한 훈련지역에 맞는 지점을 지도에서 클릭하거나 좌표를 적용하세요.');
 const result=await rpc({op:'scenario',config:{location,lat,lng,kind:$('hazard').value,duration:Number($('duration').value),secondsPerMinute:Number($('speed').value),objectives:$('objectives').value}},false);draft={...result.scenario,mode:$('trainingMode').value,org:$('myOrg').value,name:$('name').value,solo:entryKind==='solo',auto:$('autoOrg').checked};
 $('draftPanel').hidden=false;$('draftTitle').textContent=draft.title;$('draftBrief').value=draft.brief;$('generationSource').textContent=draft.source==='ai'?'AI 서술 + 모의규칙':'규칙 기반 자동 구성';$('generationNotice').textContent=result.notice;$('draftFacts').textContent=`지역: ${draft.location} · 중심 ${draft.lat.toFixed(5)}, ${draft.lng.toFixed(5)} / 고립 신고 ${draft.trapped}명 / 대피 대상 ${draft.evacuees}명 / ${draft.duration}분 / 13개 기관 슬롯`;$('draftRules').textContent=draft.notes;$('createRoom').textContent=draft.solo?'내 기관으로 연습 시작':'공동훈련방 개설·초대 링크 받기';$('draftPanel').scrollIntoView({behavior:'smooth'});
 }catch(e){toast(e.message);}finally{$('generate').disabled=false;$('generate').textContent='시나리오 자동 생성';}};
$('createRoom').onclick=async()=>{if(!draft)return;const b=$('createRoom');b.disabled=true;try{initialView=true;takeView(await rpc({op:'create',scenario:{...draft,brief:$('draftBrief').value},name:draft.name,org:draft.org,mode:draft.mode,solo:draft.solo,auto:draft.auto},false));window.scrollTo(0,0);}catch(e){toast(e.message);}finally{b.disabled=false;}};
$('offline').onclick=()=>{localMode=true;entryKind='solo';chooseEntry('solo');toast('이 기기의 개인 연습으로 전환했습니다. 다른 기관은 규칙 기반 자동 대응입니다.');};
$('inviteUrl').oninput=()=>{try{$('joinOrg').textContent='참여 기관: '+ORGS[parseInvite($('inviteUrl').value).org];}catch{$('joinOrg').textContent='기관별 초대 링크를 입력하세요.';}};
$('joinForm').onsubmit=async e=>{e.preventDefault();if(localMode)return toast('공동훈련은 서버에 연결된 주소에서 입장하세요.');try{initialView=true;takeView(await rpc({op:'join',...parseInvite($('inviteUrl').value),name:$('joinName').value},false));history.replaceState(null,'',location.pathname);window.scrollTo(0,0);}catch(e){toast(e.message);}};
$('dispatch').onclick=()=>sendCommand({type:'dispatch',job:$('ownJob').value,reason:$('ownReason').value});$('request').onclick=()=>sendCommand({type:'request',job:$('requestJob').value,reason:$('requestReason').value});$('report').onclick=()=>sendCommand({type:'report',text:$('reportText').value});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.accept)sendCommand({type:'accept',id:b.dataset.accept});if(b.dataset.decline){const reason=prompt('지원 가능 시점, 제약과 대안을 적어주세요.');if(reason)sendCommand({type:'decline',id:b.dataset.decline,reason});}if(b.dataset.share)sendCommand({type:'share',id:b.dataset.share});if(b.dataset.copy){try{await navigator.clipboard.writeText(inviteLink(b.dataset.copy));toast('해당 기관의 초대 링크를 복사했습니다.');}catch{b.parentElement.querySelector('input').select();toast('링크를 선택했습니다. 복사해서 전달하세요.');}}});
$('startExercise').onclick=()=>sendCommand({type:'start'});$('pauseExercise').onclick=()=>sendCommand({type:current.status==='paused'?'resume':'pause'});$('advanceExercise').onclick=()=>sendCommand({type:'advance',minutes:5});$('endExercise').onclick=()=>{if(confirm('합동훈련을 종료하고 강평으로 이동할까요?'))sendCommand({type:'end'});};$('controllerAuto').onchange=()=>sendCommand({type:'auto',enabled:$('controllerAuto').checked});$('inject').onclick=()=>sendCommand({type:'inject',org:$('injectOrg').value,text:$('injectText').value});$('endSolo').onclick=()=>{if(confirm('개인 연습을 종료할까요?'))sendCommand({type:'endSolo'});};
$('retryCommand').onclick=()=>sendCommand(null,true);$('saveCredential').onclick=()=>download('DREX_내접속코드_비공개.json',credential);$('downloadReport').onclick=()=>{if(current.aar)download('DREX_기관훈련보고서.html',reportHTMLDocument(),'text/html');};$('downloadRecord').onclick=()=>{const {invites,token,...record}=current;download('DREX_내기관훈련기록.json',record);};
$('showReport').onclick=()=>{if(current.status==='ended')$('aar').scrollIntoView({behavior:'smooth'});else toast('훈련 종료 후 점검표와 보고서를 확인할 수 있습니다.');};
$('sat').onclick=()=>setTiles('sat');$('street').onclick=()=>setTiles('street');$('fit').onclick=()=>mapObj?.setView([current.scenario.lat,current.scenario.lng],14);
$('restoreCredential').onchange=async e=>{try{const f=e.target.files[0];if(!f||f.size>3000)throw Error('올바른 접속코드 파일을 선택하세요.');const c=JSON.parse(await f.text());if(typeof c.token!=='string'||typeof c.id!=='string')throw Error('접속코드 형식을 확인하세요.');const old=credential,oldLocal=localMode;credential=c;localMode=c.local===true;try{const v=await rpc({op:'read',id:c.id});initialView=true;takeView(v);saveCredential();}catch(err){credential=old;localMode=oldLocal;throw err;}}catch(e){toast(e.message);}};
function exitRoom(){if(current&&!confirm('훈련방은 유지됩니다. 접속코드를 저장했나요? 이 브라우저의 접속을 종료할까요?'))return;credential=null;current=null;pending=null;localStorage.removeItem(CRED);$('workspace').hidden=true;$('entry').hidden=false;initialView=true;localMode=location.protocol==='file:';chooseEntry('solo');}
$('leave').onclick=exitRoom;$('home').onclick=exitRoom;
try{if(location.hash.includes('invite=')){chooseEntry('join');$('inviteUrl').value=location.href;$('inviteUrl').oninput();}else{const raw=localStorage.getItem(CRED);if(raw){credential=JSON.parse(raw);localMode=credential.local===true;rpc({op:'read',id:credential.id}).then(takeView).catch(e=>{toast(e.message);health();});}else health();}}catch{health();}
setInterval(poll,3000);
