import {VERSION,ROLES,PLACES,TASKS,GUIDES,create,act,view,visibleReports,restore,replay,summary} from './engine.mjs';
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='drex-cpx-0.1';let state=create(),role='hq',tab='board',archives=[];let storageOK=true;
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),5000);}
function save(){try{localStorage.setItem(KEY,JSON.stringify({state,archives}));}catch{storageOK=false;toast('자동 저장이 불가능합니다. 기록 저장 버튼으로 파일을 내려받으세요.');}}
function archive(){if(state.commands.length){archives.push({label:`${state.mode==='practice'?'연습':'실제'} ${state.time}분 · ${new Date().toLocaleString('ko-KR')}`,data:{version:VERSION,mode:state.mode,commands:state.commands}});}}
function send(c){try{state=act(state,{role,...c});save();render();return true;}catch(e){toast(e.message);return false;}}
function download(name,content,type='application/json'){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
const statusText={pending:'수락 대기',active:'실행 중',done:'완료',declined:'지원 불가'};
function render(){
 const v=view(state,role),control=role==='control';
 $('clock').textContent=String(state.time).padStart(2,'0')+':00';$('runState').textContent=state.ended?'훈련 종료':'통제자 수동 진행 · 분:초';$('modeBadge').textContent=state.mode==='practice'?'연습훈련 · 가이드 ON':'실제훈련 · 독립 판단';
 $('board').hidden=tab!=='board';$('aar').hidden=tab!=='aar';$('boardTab').classList.toggle('active',tab==='board');$('aarTab').classList.toggle('active',tab==='aar');
 $('guide').hidden=state.mode!=='practice';$('board').classList.toggle('withGuide',state.mode==='practice');
 $('guideContent').innerHTML=`<h3>${control?'훈련통제':ROLES[role]}의 연습 포인트</h3><ol>${(GUIDES[role]||['기관별 보고 공유와 지원 요청 진행을 확인하세요.','시간을 1분 또는 5분씩 진행하고 결과 보고가 도착하는 것을 확인하세요.','훈련 종료 후 기록에서 의사결정과 현장 결과를 연결해 보세요.']).map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`;
 $('reportCount').textContent=v.reports.length+'건';
 $('reports').innerHTML=v.reports.length?v.reports.slice().reverse().map(r=>`<article class="report"><div class="meta">${r.id} · ${r.time}분 · ${ROLES[r.role]} ${r.shared?'<span class="shared">· 공동 공유</span>':'· 기관 수신'}</div><p>${esc(r.text)}</p>${r.role===role&&!r.shared?`<button data-share="${r.id}" ${state.ended?'disabled':''}>공동 공유</button>`:''}</article>`).join(''):'<p class="empty">아직 공유된 보고가 없습니다. 기관별 역할에서 보고를 확인하세요.</p>';
 const coords={underpass:[330,190],care:[220,100],road:[540,195],hospital:[220,315]};
 $('markers').innerHTML=Object.entries(PLACES).map(([id,name])=>{const rs=v.reports.filter(r=>r.place===id),r=rs.at(-1),[x,y]=coords[id];return `<g><circle cx="${x}" cy="${y}" r="12" fill="${r?'#177d80':'#fff'}" stroke="#38677d" stroke-width="3"/><rect x="${x-80}" y="${y+20}" width="160" height="44" rx="7" fill="white" stroke="#d1dfe6"/><text x="${x}" y="${y+38}" text-anchor="middle" fill="#183e53">${name}</text><text x="${x}" y="${y+55}" text-anchor="middle" fill="#627e8a" style="font-size:10px">${r?`${r.time}분 보고 · ${r.shared?'공유':'기관 수신'}`:'보고 확인 필요'}</text></g>`;}).join('');
 $('resources').innerHTML=v.resources.map(r=>`<div class="resource"><strong>${r.name}</strong><div class="bar ${r.job?'active':''}"></div><small>${r.job?`${TASKS[r.job.task].name} · ${r.job.phase==='travel'?'이동':'작업'} ${r.job.remaining}분 남음`:'가용 · 새 임무 수락 가능'}</small></div>`).join('')||'<p class="empty">기관 역할을 선택해 가용 자원을 확인하세요.</p>';
 $('pendingCount').textContent=v.requests.filter(r=>r.status==='pending').length+'건 대기';
 $('requests').innerHTML=v.requests.slice().reverse().map(r=>`<article class="request"><div class="meta">${r.id} · ${r.time}분 · ${ROLES[r.from]} → ${ROLES[r.owner]}</div><strong>${TASKS[r.task].name}</strong><p>${esc(r.reason)}</p><span class="chip">${statusText[r.status]}</span>${r.reply?`<p>회신: ${esc(r.reply)}</p>`:''}${r.status==='pending'&&r.owner===role&&!state.ended?`<div class="actions"><button class="primary" data-accept="${r.id}">수락·출동</button><button data-decline="${r.id}">지원 불가·대안</button></div>`:''}</article>`).join('')||'<p class="empty">접수된 임무 요청이 없습니다.</p>';
 $('control').hidden=!control;$('orderForm').hidden=control;$('truth').textContent=`통제자 모의 상태: 고립 ${state.world.trapped}명 / 대피 잔류 ${state.world.evacuees}명 / 진입 ${state.world.closed?'통제':'미통제'} / 도로 ${state.world.blocked?'단절':'통행 가능'}`;
 document.querySelectorAll('#control button,#orderForm button').forEach(b=>b.disabled=state.ended);
 renderAAR();
}
function reviewHTML(){const m=summary(state);return `<div class="reviewBox"><strong>규칙 기반 강평 초안 · AI 평가 미연결</strong><ul><li>공유된 보고 ${m.shared}/${m.total}건. 핵심 정보가 판단 전에 전달됐는지 아래 시각을 비교하세요.</li><li>미처리 지원 요청 ${m.unresolved}건. 담당 기관의 자원 제약과 회신 여부를 확인하세요.</li><li>구조 ${m.rescued}명, 안전지점 대피 ${m.evacuated}명. 의료 수용 준비 ${state.world.medicalReady?'완료':'미완료'}. 의료 인계·치료 결과는 이 모델에서 계산하지 않습니다.</li><li>20분 이후 잔류 노출 누적 ${m.exposure}인·분. 교육용 비교 지표이며 사상자 수가 아닙니다.</li></ul><p><strong>강평 질문</strong> 당시 어떤 정보를 알고 있었습니까? 구조와 대피의 우선순위를 어떻게 합의했습니까? 다시 한다면 어떤 보고나 결정을 먼저 하겠습니까?</p><p>개선과제 작성: 담당 기관 / 개선 행동 / 완료 기한 / 다음 훈련에서 확인할 증거</p></div>`;}
function renderAAR(){
 const reveal=state.ended||role==='control',m=summary(state);
 $('aarNotice').textContent=reveal?'전체 모의 상태와 당시 보고를 함께 검토합니다. 자동 점수·합격 판정은 하지 않습니다.':'훈련 중에는 공동 판단·공유 기록만 표시합니다. 전체 결과는 종료 후 공개됩니다.';
 $('metrics').innerHTML=reveal?[[m.rescued+'명','구조 완료'],[m.evacuated+'명','안전지점 대피'],[m.shared+'건','공동 공유 보고'],[m.unresolved+'건','미처리 요청']].map(([n,l])=>`<div class="metric"><strong>${n}</strong><span>${l}</span></div>`).join(''):'';
 $('review').innerHTML=reveal?reviewHTML():'';
 const logs=reveal?state.log:state.log.filter(l=>['decision','shared'].includes(l.kind));
 $('timeline').innerHTML=logs.map(l=>`<div class="timelineRow"><time>${l.time}분</time><div>${esc(l.text)}</div></div>`).join('');
 if(reveal)$('timeline').innerHTML+=state.requests.map(r=>`<details><summary>${r.id} ${TASKS[r.task].name} · 요청 당시 근거 보고 ${r.known.length}건</summary>${r.known.map(id=>{const x=state.reports.find(z=>z.id===id);return `<p>${id} · ${x.time}분 · ${esc(x.text)}</p>`;}).join('')}</details>`).join('');
 $('branchPoint').innerHTML=state.commands.map((c,i)=>`<option value="${i}">${c.at}분 · ${i+1}번째 행동 직전 · ${ROLES[c.role]||'훈련통제'} · ${esc(({request:'임무 요청',accept:'수락',decline:'지원 불가',share:'보고 공유',advance:'시간 진행',decision:'판단 기록',inject:'상황 부여',end:'종료'})[c.type])}</option>`).join('');
 $('fork').disabled=!reveal||!state.commands.length;$('reportDownload').disabled=!reveal;
 $('archives').innerHTML=archives.map((a,i)=>`<button data-archive="${i}">${esc(a.label)} · 기록 내려받기</button>`).join('')||'보관한 실행 없음';
}
function reportDocument(){const m=summary(state);return `<!doctype html><html lang="ko"><meta charset="utf-8"><title>DREX 사후강평</title><style>body{max-width:900px;margin:40px auto;padding:20px;font:16px/1.8 system-ui;color:#183046}td,th{border:1px solid #ccd8dd;padding:8px}table{border-collapse:collapse;width:100%}h1{color:#136e78}</style><h1>DREX 지휘소훈련 사후강평</h1><p>${VERSION} · ${state.mode==='practice'?'연습훈련':'실제훈련'} · ${state.time}분 ${state.ended?'종료':'중간 기록'}</p><p>가상 지역 호우. 규칙 기반 초안이며 공식 평가 또는 실제 피해 예측이 아닙니다.</p>${reviewHTML()}<h2>결정·현장 변화 기록</h2><table><tr><th>훈련 시각</th><th>기록</th></tr>${state.log.map(l=>`<tr><td>${l.time}분</td><td>${esc(l.text)}</td></tr>`).join('')}</table><h2>요청 시점에 알고 있던 정보</h2>${state.requests.map(r=>`<h3>${r.id} · ${TASKS[r.task].name}</h3><p>${esc(r.reason)}</p><ul>${r.known.map(id=>`<li>${id}: ${esc(state.reports.find(x=>x.id===id).text)}</li>`).join('')}</ul>`).join('')}<h2>실무자 검토·개선계획</h2><table><tr><th>개선사항</th><th>담당 기관</th><th>기한</th><th>재훈련 확인 방법</th></tr><tr><td>검토 후 작성</td><td></td><td></td><td></td></tr></table><p>모델 가정: 구조·대피 1회 최대 6명, 공유 이송팀 1대. 12분 도로 단절, 우회 5분. 통제 전 5분마다 고립 2명 추가. 완료 후 자원 즉시 재배정 가정. 복귀 이동·정밀 수리계산·사상자 예측 미구현.</p></html>`;}
const roleOptions=Object.entries(ROLES).map(([id,name])=>`<option value="${id}">${name}</option>`).join('');$('role').innerHTML=roleOptions+'<option value="control">훈련통제</option>';$('target').innerHTML=roleOptions;
 $('task').innerHTML=Object.entries(TASKS).map(([id,t])=>`<option value="${id}">${t.name} → ${ROLES[t.owner]}</option>`).join('');
 $('roleHelp').innerHTML='<p>상황총괄: 정보 종합·우선순위 협의 / 소방: 구조·이송 / 경찰: 통제·도로 보고 / 보건: 의료 수용 준비 / 시설·대피지원: 대피 수요·도로 정비</p>';
 $('role').onchange=()=>{role=$('role').value;render();};$('boardTab').onclick=()=>{tab='board';render();};$('aarTab').onclick=()=>{tab='aar';render();};$('help').onclick=()=>$('helpDialog').showModal();$('closeHelp').onclick=()=>$('helpDialog').close();
 $('new').onclick=()=>$('setup').showModal();$('start').onclick=e=>{e.preventDefault();archive();state=create(document.querySelector('[name="mode"]:checked').value);role='hq';$('role').value=role;tab='board';save();render();$('setup').close();};
 $('orderForm').onsubmit=e=>{e.preventDefault();if(send({type:'request',task:$('task').value,reason:$('reason').value})){$('reason').value='';toast('요청했습니다. 담당 기관 역할에서 수락·출동을 진행하세요.');}};
 $('decision').onclick=()=>{if(send({type:'decision',reason:$('reason').value}))$('reason').value='';};
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.share)send({type:'share',id:b.dataset.share});if(b.dataset.accept)send({type:'accept',id:b.dataset.accept});if(b.dataset.decline){const reason=prompt('지원 불가 사유와 대안을 입력하세요.');if(reason)send({type:'decline',id:b.dataset.decline,reason});}if(b.dataset.minutes)send({type:'advance',minutes:Number(b.dataset.minutes)});if(b.dataset.archive!==undefined){const a=archives[Number(b.dataset.archive)];download('DREX_CPX_archive.json',JSON.stringify(a.data,null,2));}});
 $('inject').onclick=()=>{if(send({type:'inject',target:$('target').value,reason:$('injectText').value}))$('injectText').value='';};$('end').onclick=()=>{if(confirm('현재 시점에서 종료하고 사후강평을 진행할까요?')){send({type:'end'});tab='aar';render();}};
 $('export').onclick=()=>download('DREX_CPX_record.json',JSON.stringify({version:VERSION,mode:state.mode,commands:state.commands},null,2));
 $('import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>3000000)throw Error('3MB 이하 기록만 불러올 수 있습니다.');const loaded=restore(JSON.parse(await f.text()));archive();state=loaded;save();render();toast('기록을 재실행해 복원했습니다.');}catch(err){toast('불러오기 실패: '+err.message);}e.target.value='';};
 $('fork').onclick=()=>{const n=Number($('branchPoint').value);if(confirm('현재 실행을 보관하고 선택 지점 직전부터 다시 훈련할까요?')){const next=replay(state.mode,state.commands.slice(0,n));archive();state=next;tab='board';save();render();toast('분기 재훈련을 시작했습니다. 이전 기록은 사후강평에서 내려받을 수 있습니다.');}};
 $('reportDownload').onclick=()=>download('DREX_CPX_AAR.html',reportDocument(),'text/html');
 try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);state=restore(parsed.state);archives=Array.isArray(parsed.archives)?parsed.archives:[];}else $('setup').showModal();}catch{storageOK=false;$('setup').showModal();toast('저장 기록을 읽지 못했습니다. 새 훈련으로 시작합니다.');}
 render();
